const chest = [
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/KYdI4KXXCTGkuP",
    id: "3294",
    instructions: [
      "Start in a push-up position with your hands slightly wider than shoulder-width apart.",
      "Extend one arm straight out to the side, parallel to the ground.",
      "Lower your body by bending your elbows, keeping your back straight and core engaged.",
      "Push back up to the starting position.",
      "Repeat on the other side, extending the opposite arm out to the side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
    name: "archer push up",
    secondaryMuscles: ["triceps", "shoulders", "core"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/uDBWYyFSAjoEJA",
    id: "0009",
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with your palms facing down and your arms fully extended.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Pause for a moment, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted chest dip (kneeling)",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/QG0tenYi4kGjs0",
    id: "1716",
    instructions: [
      "Sit on a stability ball with your feet flat on the ground and your back straight.",
      "Hold a stability ball with both hands and extend your arms straight out in front of you.",
      "Slowly lower the stability ball towards your  chest, feeling a stretch in your pectoral muscles.",
      "Hold the stretch for a few seconds, then slowly return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted seated pectoralis major stretch with stability ball",
    secondaryMuscles: ["shoulders", "triceps"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/kzYlSCF1Aa7n1J",
    id: "2364",
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with a wide grip and keep your elbows slightly bent.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Push yourself back up to the starting position by extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted wide-grip chest dip (kneeling)",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/i4MteCj8pdxFaz",
    id: "1254",
    instructions: [
      "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
      "Grasp the band handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Extend your arms fully, pushing the bands away from your chest.",
      "Slowly lower the bands back down to your chest, keeping your elbows at a 90-degree angle.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "band bench press",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/GgPxdjMCnxcaa2",
    id: "0989",
    instructions: [
      "Attach the band to a sturdy anchor point at chest height.",
      "Stand with your side facing the anchor point and grab the band with one hand.",
      "Step away frnd repeat for the desired number of repetitions.",
      "Switch sides and repeat the exercise with the other hand.",
    ],
    name: "band one arm twisting chest press",
    secondaryMuscles: ["shoulders", "triceps"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/t9b1UrHpGn4GaW",
    id: "0025",
    instructions: [
      "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
      "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
      "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
      "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
      "Pause for a moment when the barbell touches your chest.",
      "Push the barbell back up to the starting position by extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell bench press",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/w8HAkF64kho07y",
    id: "0033",
    instructions: [
      "Lie on a decline bench with your feet secured and your head lower than your hips.",
      "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
      "Unrack the barbell and lower it slowly towards your chest, keeping your elbows tucked in.",
      "Pause for a moment at the bottom, then push the barbell back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell decline bench press",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/MNunVi8OWwZfEn",
    id: "1255",
    instructions: [
      "Lie down on a decline bench with your head lower than your hips and your feet secured.",
      "Hold the barbell with a pronated grip (palms facing away from you) and your hands slightly wider than shoulder-width apart.",
      "Extend your arms above your chest, keeping a slight bend in your elbows.",
      "Lower the barbell in an arc motion behind your head, feeling a stretch in your chest and shoulders.",
      "Pause for a moment, then return the barbell to the starting position by reversing the motion.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell decline pullover",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/jCekiHUpTl9kM8",
    id: "0036",
    instructions: [
      "Lie on a decline bench with your feet secured and your head lower than your hips.",
      "Grasp the barbell with a wide grip, slightly wider than shoulder-width apart.",
      "Lower the barbell to your chest, keeping your elbows out to the sides.",
      "Push the barbell back up to the starting position, fully extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell decline wide-grip press",
    secondaryMuscles: ["triceps", "shoulders"],
    target: "pectorals",
  },
];
