export const rapidApiKey = "0a648ef4ecmshdc9d7b8445fe9b1p1db2c4jsn87a1f54c290d";

export const sliderImages = [
  require("../assets/images/young-fitness-man.png"),
  require("../assets/images/slide2.jpeg"),
  require("../assets/images/slide3.jpg"),
  require("../assets/images/slide4.jpg"),
  require("../assets/images/slide5.jpg"),
  require("../assets/images/slide6.jpg"),
  require("../assets/images/slide7.jpg"),
  require("../assets/images/slide8.jpg"),
];

export const bodyParts = [
  { name: "back", image: require("../assets/images/back1.jpg") },
  { name: "cardio", image: require("../assets/images/hayley-kim.jpg") },
  { name: "chest", image: require("../assets/images/chest1.jpg") },
  { name: "lower arms", image: require("../assets/images/anastase-m.jpg") },
  { name: "lower legs", image: require("../assets/images/anastase-m.jpg") },
  { name: "neck", image: require("../assets/images/anastase-m.jpg") },
  { name: "shoulders", image: require("../assets/images/anastase-m.jpg") },
  { name: "upper arms", image: require("../assets/images/anastase-m.jpg") },
  { name: "upper legs", image: require("../assets/images/anastase-m.jpg") },
  { name: "waist", image: require("../assets/images/anastase-m.jpg") },
];

export const dommyData =  [
  {
    id: "3220",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515386/Exercise%20Gif/nobtghbjitl3oxr0ep8w.gif",
    name: "astride jumps (male)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Bend your knees and lower your body into a squat position.",
      "Jump explosively upwards, extending your legs and arms.",
      "While in the air, spread your legs apart and bring your arms out to the sides.",
      "Land softly with your feet shoulder-width apart, bending your knees to absorb the impact.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3672",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515389/Exercise%20Gif/skleyc8louoh80y7d33x.gif",
    name: "back and forth step",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Step forward with your right foot, bending your knee and lowering your body into a lunge position.",
      "Push off with your right foot and step back to the starting position.",
      "Repeat the movement with your left foot, alternating legs with each step.",
      "Continue stepping back and forth, maintaining a steady pace.",
      "Repeat for the desired duration or number of repetitions.",
    ],
  },
  {
    id: "3360",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515390/Exercise%20Gif/vwgmojsgugluajxbvokv.gif",
    name: "bear crawl",
    target: "cardiovascular system",
    secondaryMuscles: ["core", "shoulders", "triceps"],
    instructions: [
      "Start on all fours with your hands directly under your shoulders and your knees directly under your hips.",
      "Lift your knees slightly off the ground, keeping your back flat and your core engaged.",
      "Move your right hand and left foot forward simultaneously, followed by your left hand and right foot.",
      "Continue crawling forward, alternating your hand and foot movements.",
      "Maintain a steady pace and keep your core tight throughout the exercise.",
      "Continue for the desired distance or time.",
    ],
  },
  {
    id: "1160",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515393/Exercise%20Gif/st1rslm5hosc0wubpxqc.gif",
    name: "burpee",
    target: "cardiovascular system",
    secondaryMuscles: [
      "quadriceps",
      "hamstrings",
      "calves",
      "shoulders",
      "chest",
    ],
    instructions: [
      "Start in a standing position with your feet shoulder-width apart.",
      "Lower your body into a squat position by bending your knees and placing your hands on the floor in front of you.",
      "Kick your feet back into a push-up position.",
      "Perform a push-up, keeping your body in a straight line.",
      "Jump your feet back into the squat position.",
      "Jump up explosively, reaching your arms overhead.",
      "Land softly and immediately lower back into a squat position to begin the next repetition.",
    ],
  },
  {
    id: "2331",
    bodyPart: "cardio",
    equipment: "leverage machine",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515395/Exercise%20Gif/zpzyybihapeflugsksw8.gif",
    name: "cycle cross trainer",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes"],
    instructions: [
      "Adjust the seat height and position yourself on the cycle cross trainer.",
      "Place your feet on the pedals and grip the handlebars.",
      "Start pedaling in a smooth and controlled motion.",
      "Maintain a steady pace and increase the resistance if desired.",
      "Continue pedaling for the desired duration of your cardio workout.",
    ],
  },
  {
    id: "1201",
    bodyPart: "cardio",
    equipment: "dumbbell",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515396/Exercise%20Gif/soiufod4pkdpaszjmdgv.gif",
    name: "dumbbell burpee",
    target: "cardiovascular system",
    secondaryMuscles: [
      "quadriceps",
      "hamstrings",
      "calves",
      "shoulders",
      "triceps",
      "core",
    ],
    instructions: [
      "Start in a standing position with your feet shoulder-width apart and a dumbbell in each hand.",
      "Lower your body into a squat position, placing the dumbbells on the ground in front of you.",
      "Kick your feet back into a push-up position, keeping your body in a straight line.",
      "Perform a push-up, bending your elbows and lowering your chest towards the ground.",
      "Jump your feet back towards your hands, landing in a squat position.",
      "Stand up explosively, lifting the dumbbells off the ground and bringing them to your shoulders.",
      "Press the dumbbells overhead, fully extending your arms.",
      "Lower the dumbbells back to your shoulders and repeat the entire sequence for the desired number of repetitions.",
    ],
  },
  {
    id: "3221",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515399/Exercise%20Gif/z4w8fmtvnclezjrquatd.gif",
    name: "half knee bends (male)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Bend your knees and lower your body down as if you were sitting back into a chair.",
      "Keep your chest up and your weight in your heels.",
      "Pause for a moment at the bottom, then push through your heels to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3636",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515400/Exercise%20Gif/ftguhfjf8ffbmf1s0mpm.gif",
    name: "high knee against wall",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Stand facing a wall with your feet hip-width apart.",
      "Place your hands on the wall for support.",
      "Engage your core and lift your right knee up towards your chest, while keeping your left foot on the ground.",
      "Quickly switch legs, bringing your left knee up towards your chest and lowering your right foot back down.",
      "Continue alternating legs in a running motion, bringing your knees up as high as possible.",
      "Maintain a fast pace and keep your upper body stable throughout the exercise.",
      "Repeat for the desired duration or number of repetitions.",
    ],
  },
  {
    id: "0501",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515402/Exercise%20Gif/ipckjc9zq2pivbitx6mw.gif",
    name: "jack burpee",
    target: "cardiovascular system",
    secondaryMuscles: [
      "quadriceps",
      "hamstrings",
      "calves",
      "shoulders",
      "triceps",
      "core",
    ],
    instructions: [
      "Start in a standing position with your feet shoulder-width apart.",
      "Lower your body into a squat position, placing your hands on the ground in front of you.",
      "Kick your feet back, landing in a push-up position.",
      "Perform a push-up, lowering your chest to the ground and then pushing back up.",
      "Jump your feet forward, landing in a squat position.",
      "Jump up explosively, reaching your arms overhead.",
      "Land softly and immediately lower back into the squat position to begin the next repetition.",
    ],
  },
  {
    id: "3224",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515406/Exercise%20Gif/slxtxghizpiiay7rb6ww.gif",
    name: "jack jump (male)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "calves"],
    instructions: [
      "Stand with your feet together and your arms by your sides.",
      "Jump up, spreading your feet apart and raising your arms above your head.",
      "As you land, quickly jump back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "2612",
    bodyPart: "cardio",
    equipment: "rope",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515409/Exercise%20Gif/e7aqqkz3gcfoisxyahye.gif",
    name: "jump rope",
    target: "cardiovascular system",
    secondaryMuscles: ["calves", "quadriceps", "hamstrings", "glutes"],
    instructions: [
      "Hold the handles of the jump rope with your hands, palms facing inward.",
      "Stand with your feet shoulder-width apart and knees slightly bent.",
      "Swing the rope over your head and jump over it as it comes towards your feet.",
      "Land softly on the balls of your feet and repeat the jump as the rope comes around again.",
      "Continue jumping for the desired duration or number of repetitions.",
    ],
  },
  {
    id: "0630",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515415/Exercise%20Gif/uymgzefkai7a88oj9byh.gif",
    name: "mountain climber",
    target: "cardiovascular system",
    secondaryMuscles: ["core", "shoulders", "triceps"],
    instructions: [
      "Start in a high plank position with your hands directly under your shoulders and your body in a straight line.",
      "Engage your core and bring your right knee towards your chest, then quickly switch and bring your left knee towards your chest.",
      "Continue alternating legs in a running motion, keeping your hips low and your core engaged.",
      "Maintain a steady pace and breathe evenly throughout the exercise.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3638",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515418/Exercise%20Gif/fnhgvvfpi96ztpkbih9k.gif",
    name: "push to run",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Start in a push-up position with your hands shoulder-width apart and your body in a straight line.",
      "Lower your chest towards the ground by bending your elbows, keeping your body straight.",
      "Push through your hands to extend your arms and return to the starting position.",
      "Quickly bring one knee towards your chest, then quickly switch and bring the other knee towards your chest.",
      "Continue alternating knees as fast as you can while maintaining good form.",
      "Continue for the desired duration or number of repetitions.",
    ],
  },
  {
    id: "0685",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515419/Exercise%20Gif/xlkmt0mor52bymbumawm.gif",
    name: "run",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Start by standing upright with your feet hip-width apart.",
      "Engage your core and keep your upper body relaxed.",
      "Begin jogging in place, lifting your knees up towards your chest and landing softly on the balls of your feet.",
      "Maintain a steady pace and continue jogging for the desired duration or distance.",
      "Remember to breathe deeply and maintain good posture throughout the exercise.",
    ],
  },
  {
    id: "0684",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515421/Exercise%20Gif/olbcm97ptr21e8eus9vl.gif",
    name: "run (equipment)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Start by standing upright with your feet hip-width apart.",
      "Engage your core and keep your upper body relaxed.",
      "Begin jogging in place, lifting your knees up towards your chest and landing softly on the balls of your feet.",
      "Maintain a steady pace and continue jogging for the desired duration or distance.",
      "Remember to breathe deeply and maintain good posture throughout the exercise.",
    ],
  },
  {
    id: "3219",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515424/Exercise%20Gif/u5lfq9psalzzcnjy0pes.gif",
    name: "scissor jumps (male)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Jump off the ground and simultaneously cross your right leg in front of your left leg.",
      "As you land, quickly switch legs, crossing your left leg in front of your right leg.",
      "Continue alternating legs and jumping as quickly as possible.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3222",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515426/Exercise%20Gif/bd7cto3ffteruvp2l6zk.gif",
    name: "semi squat jump (male)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Bend your knees and lower your body into a squat position.",
      "Jump explosively, extending your hips and knees while swinging your arms for momentum.",
      "Land softly on the balls of your feet and immediately go into the next repetition.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3656",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515428/Exercise%20Gif/eojgrkzrmksutrxmufbx.gif",
    name: "short stride run",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Find an open space or a treadmill to perform the exercise.",
      "Stand tall with your feet hip-width apart.",
      "Start jogging in place, lifting your knees high and pumping your arms.",
      "After a few seconds, start taking short strides forward, maintaining a quick pace.",
      "Continue running with short strides for the desired duration or distance.",
    ],
  },
  {
    id: "3361",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515430/Exercise%20Gif/fkckci7kirzkti0enqbl.gif",
    name: "skater hops",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Bend your knees slightly and jump to the right, landing on your right foot.",
      "As you land, swing your left leg behind your right leg and tap the ground with your left toes.",
      "Immediately jump to the left, landing on your left foot.",
      "As you land, swing your right leg behind your left leg and tap the ground with your right toes.",
      "Continue alternating sides, jumping and tapping the ground with each leg.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3671",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515432/Exercise%20Gif/wunj0xrhkp7p8uxlosd1.gif",
    name: "ski step",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart.",
      "Bend your knees slightly and keep your back straight.",
      "Jump to the right, landing on your right foot while swinging your left leg behind your right leg.",
      "Immediately jump to the left, landing on your left foot while swinging your right leg behind your left leg.",
      "Continue alternating jumps from side to side, mimicking a skiing motion.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3223",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515435/Exercise%20Gif/zmcc7bduknxebv4t1qsi.gif",
    name: "star jump (male)",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Stand with your feet shoulder-width apart and your arms by your sides.",
      "Bend your knees slightly and jump up explosively.",
      "As you jump, spread your legs and extend your arms out to the sides, forming a star shape with your body.",
      "Land softly on the balls of your feet with your knees slightly bent.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "2138",
    bodyPart: "cardio",
    equipment: "stationary bike",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515437/Exercise%20Gif/jm1xjdlv7xll0atwmhgp.gif",
    name: "stationary bike run v. 3",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Adjust the seat height and position to ensure proper alignment.",
      "Place your feet on the pedals and secure them with the straps if available.",
      "Start pedaling at a comfortable pace.",
      "Maintain a steady rhythm and increase the resistance as desired.",
      "Engage your core muscles to maintain stability and proper posture.",
      "Continue pedaling for the desired duration of your workout.",
      "Gradually decrease the resistance and slow down before coming to a complete stop.",
      "Stretch your legs and cool down after the workout.",
    ],
  },
  {
    id: "0798",
    bodyPart: "cardio",
    equipment: "leverage machine",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515439/Exercise%20Gif/oqcv6fa0tswgl5u9wen6.gif",
    name: "stationary bike walk",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Adjust the seat height and position on the stationary bike to ensure proper alignment.",
      "Place your feet on the pedals and secure them with the straps if available.",
      "Start pedaling at a comfortable pace, keeping your back straight and core engaged.",
      "Maintain a steady rhythm and increase the resistance level if desired.",
      "Continue pedaling for the desired duration of your cardio workout.",
      "Cool down by gradually reducing your pace and resistance level.",
      "Stretch your leg muscles after the workout to prevent tightness and promote recovery.",
    ],
  },
  {
    id: "3318",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515442/Exercise%20Gif/jz4pzhio6jaatykc4ovy.gif",
    name: "swing 360",
    target: "cardiovascular system",
    secondaryMuscles: ["shoulders", "core"],
    instructions: [
      "Stand with your feet shoulder-width apart and knees slightly bent.",
      "Hold your arms straight out in front of you, parallel to the ground.",
      "Engage your core and swing your arms in a circular motion, rotating your torso as you do so.",
      "Continue the circular motion, swinging your arms and rotating your torso for the desired number of repetitions.",
      "Remember to breathe throughout the exercise.",
    ],
  },
  {
    id: "2141",
    bodyPart: "cardio",
    equipment: "elliptical machine",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515445/Exercise%20Gif/atsj0gyf5pzukrwf0ph8.gif",
    name: "walk elliptical cross trainer",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Adjust the resistance level and incline of the elliptical machine to your desired settings.",
      "Step onto the pedals of the machine and grip the handles lightly.",
      "Begin by pushing down with your feet and pulling the handles towards your body.",
      "Continue this motion, alternating between pushing and pulling, to simulate a walking or running motion.",
      "Maintain a steady pace and keep your core engaged throughout the exercise.",
      "Continue for the desired duration of your cardio workout.",
      "Gradually decrease the intensity and speed of the machine before stepping off.",
    ],
  },
  {
    id: "3655",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515457/Exercise%20Gif/fjii8vowdutxiyrsdk18.gif",
    name: "walking high knees lunge",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Stand with your feet hip-width apart.",
      "Lift your right knee up towards your chest as high as you can while balancing on your left leg.",
      "Step forward with your right foot and lower your body into a lunge position, bending both knees to a 90-degree angle.",
      "Push off with your right foot and bring your left knee up towards your chest.",
      "Step forward with your left foot and lower your body into a lunge position.",
      "Continue alternating legs and lunging forward, keeping your core engaged and maintaining a steady pace.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    id: "3666",
    bodyPart: "cardio",
    equipment: "leverage machine",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515480/Exercise%20Gif/sy7hl9slp2v5aqtaloqh.gif",
    name: "walking on incline treadmill",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Adjust the incline level on the treadmill to your desired intensity.",
      "Stand on the treadmill with your feet shoulder-width apart.",
      "Start walking at a comfortable pace, ensuring that you maintain proper form.",
      "Engage your core muscles and keep your back straight throughout the exercise.",
      "Continue walking on the incline treadmill for the desired duration of your cardio workout.",
      "Gradually decrease the incline and speed of the treadmill to cool down before stopping.",
    ],
  },
  {
    id: "2311",
    bodyPart: "cardio",
    equipment: "stepmill machine",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515486/Exercise%20Gif/mnayv2iewvg2euuujb0c.gif",
    name: "walking on stepmill",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    instructions: [
      "Adjust the stepmill machine to a comfortable level.",
      "Step onto the machine and place your hands on the handrails for support.",
      "Start walking by placing one foot on a step and then the other, alternating between legs.",
      "Maintain an upright posture and engage your core muscles.",
      "Continue walking for the desired duration or distance.",
      "Gradually increase the intensity or speed as you become more comfortable with the exercise.",
      "Remember to cool down and stretch after completing the exercise.",
    ],
  },
  {
    id: "3637",
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl:
      "https://res.cloudinary.com/djt6ixhup/image/upload/v1712515499/Exercise%20Gif/cevxn8aufkhixb18gdy3.gif",
    name: "wheel run",
    target: "cardiovascular system",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    instructions: [
      "Start in a plank position with your hands on the wheel and your body straight.",
      "Engage your core and start rolling the wheel forward by extending your arms.",
      "Continue rolling until your body is fully extended and your arms are overhead.",
      "Reverse the movement by pulling the wheel back towards your body, using your core and arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
];
