export const rapidApiKey = "0a648ef4ecmshdc9d7b8445fe9b1p1db2c4jsn87a1f54c290d";

export const sliderImages = [
  require("../assets/images/young-fitness-man.png"),
  require("../assets/images/slide2.jpeg"),
  require("../assets/images/slide3.jpg"),
  require("../assets/images/slide4.jpg"),
  require("../assets/images/slide5.jpg"),
  require("../assets/images/slide6.jpg"),
  require("../assets/images/slide7.jpg"),
  require("../assets/images/slide8.jpg"),
];

export const bodyParts = [
  { name: "back", image: require("../assets/images/back1.jpg") },
  { name: "cardio", image: require("../assets/images/hayley-kim.jpg") },
  { name: "chest", image: require("../assets/images/chest1.jpg") },
  { name: "lower arms", image: require("../assets/images/anastase-m.jpg") },
  { name: "lower legs", image: require("../assets/images/anastase-m.jpg") },
  { name: "neck", image: require("../assets/images/anastase-m.jpg") },
  { name: "shoulders", image: require("../assets/images/anastase-m.jpg") },
  { name: "upper arms", image: require("../assets/images/anastase-m.jpg") },
  { name: "upper legs", image: require("../assets/images/anastase-m.jpg") },
  { name: "waist", image: require("../assets/images/anastase-m.jpg") },
];

export const dommyData = [
  {
    bodyPart: "lower arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/nQo8Bw-xNdEA22",
    id: "0994",
    instructions: [
      "Sit on a bench or chair with your feet flat on the ground.",
      "Hold the band with an overhand grip, palms facing down, and wrap it around your fingers.",
      "Rest your forearms on your thighs, with your wrists hanging off the edge.",
      "Slowly curl your wrists upward, squeezing your forearms.",
      "Pause for a moment at the top, then slowly lower your wrists back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "band reverse wrist curl",
    secondaryMuscles: ["forearms"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/iUmXqT-Rs7kUjm",
    id: "1016",
    instructions: [
      "Sit on a bench or chair with your feet flat on the ground.",
      "Hold the band with both hands, palms facing up, and rest your forearms on your thighs.",
      "Slowly curl your wrists upward, squeezing your forearms.",
      "Pause for a moment at the top, then slowly lower your wrists back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "band wrist curl",
    secondaryMuscles: ["biceps", "triceps"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/Z8htak8AtO4cMj",
    id: "1411",
    instructions: [
      "Sit on a bench with your feet flat on the ground and your forearms resting on your thighs, palms facing down.",
      "Hold a barbell with an overhand grip, hands shoulder-width apart.",
      "Lower the barbell towards the ground by flexing your wrists, keeping your forearms stationary.",
      "Pause for a moment at the bottom, then slowly raise the barbell back up by extending your wrists.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell palms down wrist curl over a bench",
    secondaryMuscles: ["biceps", "brachialis"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/OYKrPSVL7yJiCa",
    id: "1412",
    instructions: [
      "Sit on a bench with your feet flat on the ground and hold a barbell with an underhand grip, palms facing up.",
      "Rest your forearms on the bench, allowing your wrists to hang off the edge.",
      "Keeping your forearms stationary, exhale and curl your wrists upwards as far as possible.",
      "Hold the contracted position for a brief pause, then inhale and slowly lower the barbell back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell palms up wrist curl over a bench",
    secondaryMuscles: ["biceps", "shoulders"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/01wk2dMJH0LZwg",
    id: "0079",
    instructions: [
      "Sit on a bench with your feet flat on the ground and your knees bent.",
      "Hold a barbell with an overhand grip, palms facing down, and your hands shoulder-width apart.",
      "Rest your forearms on your thighs, allowing your wrists to hang off the edge.",
      "Keeping your forearms stationary, exhale and curl your wrists upward as far as possible.",
      "Hold the contracted position for a brief pause, then inhale and slowly lower the barbell back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell revers wrist curl v. 2",
    secondaryMuscles: ["biceps", "brachialis"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/a5cNqyJsFyYqWD",
    id: "0082",
    instructions: [
      "Sit on a bench with your feet flat on the ground and hold a barbell with an overhand grip, palms facing down.",
      "Rest your forearms on your thighs, allowing your wrists to hang off the edge.",
      "Slowly curl your wrists upward, bringing the barbell towards your body.",
      "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell reverse wrist curl",
    secondaryMuscles: ["biceps", "brachialis"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/d8buwG0dw70UKU",
    id: "0104",
    instructions: [
      "Stand up straight with your feet shoulder-width apart and hold a barbell with an overhand grip.",
      "Rest the barbell on the back of your hands with your palms facing down and your fingers pointing towards your body.",
      "Keeping your upper arms stationary, exhale and curl your wrists upwards as far as possible.",
      "Hold the contracted position for a brief pause, then inhale and slowly lower the barbell back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell standing back wrist curl",
    secondaryMuscles: ["biceps", "shoulders"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/hlaT8sCX2uGjpC",
    id: "0126",
    instructions: [
      "Sit on a bench with your feet flat on the ground and your forearms resting on your thighs, holding a barbell with an underhand grip.",
      "Allow the barbell to roll down to your fingertips, keeping your wrists straight.",
      "Slowly curl the barbell up towards your forearms by flexing your wrists.",
      "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell wrist curl",
    secondaryMuscles: ["biceps", "brachialis"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/CLQK72yTzcnAcw",
    id: "0125",
    instructions: [
      "Sit on a bench with your feet flat on the ground and your knees bent.",
      "Hold a barbell with an underhand grip, palms facing up, and your hands shoulder-width apart.",
      "Rest your forearms on your thighs, allowing your wrists to hang off the edge.",
      "Slowly curl your wrists upward, bringing the barbell towards your forearms.",
      "Pause for a moment at the top, then slowly lower the barbell back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell wrist curl v. 2",
    secondaryMuscles: ["biceps", "brachialis"],
    target: "forearms",
  },
  {
    bodyPart: "lower arms",
    equipment: "cable",
    gifUrl: "https://v2.exercisedb.io/image/X--4uwCU5-wUCj",
    id: "0210",
    instructions: [
      "Attach a cable to a low pulley and sit on a bench facing the cable machine.",
      "Grasp the cable handle with an overhand grip, palms facing down.",
      "Rest your forearms on your thighs, with your wrists hanging off the edge.",
      "Keeping your forearms stationary, exhale and curl your wrists upward as far as possible.",
      "Pause for a moment at the top, then inhale and slowly lower your wrists back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "cable reverse wrist curl",
    secondaryMuscles: ["forearms", "wrists"],
    target: "forearms",
  },
];
